### PR TITLE
Small improvement in Readme

### PR DESCRIPTION
**Pull request by slintes**
#### Why we need this PR
- improve Readme
- test tide

#### Changes made
Improved wording for NHC

### CODE REVIEW

**Comment by slintes** [comment]
not needed for doc only changes

/override ci/prow/4.12-openshift-e2e 
/override ci/prow/4.12-test 
/override ci/prow/4.13-openshift-e2e 
/override ci/prow/4.13-test 
/override ci/prow/4.14-openshift-e2e 
/override ci/prow/4.14-test 
/override ci/prow/4.15-openshift-e2e 
/override ci/prow/4.15-test

**Review by clobrano — APPROVED** [review]

**Pull request merged**
