### PR TITLE
Fix test file name

### PR DESCRIPTION
**Pull request by slintes**
nothing to add to the title 😎

### CODE REVIEW

**Comment by beekhof** [comment]
I don't see how renaming the test file could cause the failures which seem to be coming from must-gather. Is it appropriate to merge anyway?

**Comment by slintes** [comment]
> I don't see how renaming the test file could cause the failures which seem to be coming from must-gather. Is it appropriate to merge anyway?

yep, just double checked that the actual e2e tests run successfully

/override ci/prow/e2e-test

**Pull request merged**
