### PR TITLE
Update ext remediation rule

### PR DESCRIPTION
**Pull request by slintes**
Allow NHC to watch and update the CR

### CODE REVIEW

**Comment by mshitrit** [comment]
/lgtm
/hold
Giving others chance to review.

IIUC the context for this PR is the `Processing` condition and nhc-time-out  annotation right ?

**Comment by slintes** [comment]
> IIUC the context for this PR is the Processing condition and nhc-time-out annotation right ?

correct 👍🏼 

/hold cancel

**Pull request merged**
