### PR TITLE
Updating SNR readme - noting it replaces Poison Pill

### PR DESCRIPTION
**Pull request by mshitrit**

### CODE REVIEW

**Comment by slintes** [comment]
Do we really need / want this? We want to get rid of the old name, this adds it at a new place 🤷🏼‍♂️ IMHO the deprecation notice on PP is good enough.

**Comment by mshitrit** [comment]
> Do we really need / want this? We want to get rid of the old name, this adds it at a new place 🤷🏼‍♂️ IMHO the deprecation notice on PP is good enough.

No objection on my part.

@razo7 any objection that I'll close this PR ?

**Comment by razo7** [comment]
> > Do we really need / want this? We want to get rid of the old name, this adds it at a new place 🤷🏼‍♂️ IMHO the deprecation notice on PP is good enough.
> 
> No objection on my part.
> 
> @razo7 any objection that I'll close this PR ?

None. The deprecation notice is indeed good enough.

**Comment by mshitrit** [comment]
Per [discussion](https://github.com/medik8s/self-node-remediation/pull/41#issuecomment-1200408879) this PR is unneeded.

**Pull request closed without merging**
