### PR TITLE
[TEST ONLY] log last Peer check time

### PR DESCRIPTION
**Pull request by clobrano**
!!TEST ONLY!!

do not merge

### CODE REVIEW

**Comment by clobrano** [comment]
> @clobrano: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/4.15-openshift-e2e 	[a5ad462](https://github.com/medik8s/self-node-remediation/commit/a5ad46260302716c3e37a5fb2b28a6570d832ef7) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/medik8s_self-node-remediation/222/pull-ci-medik8s-self-node-remediation-main-4.15-openshift-e2e/1803470095385628672) 	true 	`/test 4.15-openshift-e2e`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=medik8s&repo=self-node-remediation&pr=222). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:clobrano).

DS pods do not seem to have checked their peers.

In this test version I added [a log with the timestamp of the last performed peer check](https://github.com/medik8s/self-node-remediation/pull/222/files#diff-ccf33ddf3e50ffe2c0781beff74d5547114c84631b50e6237a804b380c178152R70-R102) for each DS. 

[SNR-PR222 CI logs](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/medik8s_self-node-remediation/222/pull-ci-medik8s-self-node-remediation-main-4.15-openshift-e2e/1803470095385628672)

The test passed, the returned failure seems to come from some clean up

[SNR-PR222 SNR DS logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/medik8s_self-node-remediation/222/pull-ci-medik8s-self-node-remediation-main-4.15-openshift-e2e/1803470095385628672/artifacts/openshift-e2e/gather-extra/artifacts/pods/)

API Server connectivity is cut from time 17:45.16 to 17:50.38 (counted in between the two Node's `uptime` measurements), and all DS show the api check succeeded in the same interval, and the `last peer check` timestamp was never updated.

**Comment by slintes** [comment]
superseeded by and partly included in #226 

/close

**Pull request closed without merging**
